# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-action
name: Birthday Update

on:
  schedule:
    - cron: '00 18 * * *' 
  workflow_dispatch:
jobs:
  personal-channel:
    env:
      DAILY_SENT_FILE_NAME: "daily-private.json"
      MONTHLY_SENT_FILE_NAME: "montly-private.json"
      BOT_TOKEN: "ODMxNTMyMTQ1NDUzMzAxNzcw.YHWmqA.X3k3mfLzhewi3iJg2OL_upD-OTE"
      CERTIFICATE_PATH: "private-certificate.json"
      DATABASE_URL: "https://birthday-reminder-bb6f8-default-rtdb.europe-west1.firebasedatabase.app/"
      STORAGE_BUCKET: "gs://birthday-reminder-bb6f8.appspot.com"
      DB_REFERENCE: "birthday-reminder-bb6f8-default-rtdb"
      LOG_CHANNEL_ID: "958625740956520458"
      TARGET_CHANNEL: "958460165533859900"
    runs-on : windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Running the program
        run: ".\\main.exe"

  # You may pin to the exact commit or the version.
  # uses: reloc8/action-push-local-changes@db6ff4a3eac620530c970af02229a260240aa8aa
      - name : chnaged Readme.md
        run : |
          $FileName = "Readme.md"
          if (Test-Path $FileName) {
            Remove-Item $FileName
          }
          "Last Run at ``" + $(get-date) + "`` UTC" > Readme.md
      - name: action-push-local-changes to Master
        uses: reloc8/action-push-local-changes@1.0.0
        with:
          commit-message: Daily_messgaes.json changed
  general-channel:
      needs: personal-channel
      env:
        DAILY_SENT_FILE_NAME: "daily-general.json"
        MONTHLY_SENT_FILE_NAME: "montly-general.json"
        BOT_TOKEN: "ODMxNTMyMTQ1NDUzMzAxNzcw.YHWmqA.X3k3mfLzhewi3iJg2OL_upD-OTE"
        CERTIFICATE_PATH: "general-certificate.json"
        DATABASE_URL: "https://fir-authsuhrut.firebaseio.com"
        STORAGE_BUCKET: "firebaseauthsuhrut.appspot.com"
        DB_REFERENCE: "fir-authsuhrut"
        LOG_CHANNEL_ID: "876070119867031592"
        TARGET_CHANNEL: "831833834671702086"
        #Testing_channel_id=831911965643112489
        #Main Channel id=831833834671702086
      runs-on : windows-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3.0.0
        - name: Running the program
          run: ".\\main.exe"

    # You may pin to the exact commit or the version.
    # uses: reloc8/action-push-local-changes@db6ff4a3eac620530c970af02229a260240aa8aa
        - name : chnaged Readme.md
          run : |
            $FileName = "Readme.md"
            if (Test-Path $FileName) {
              Remove-Item $FileName
            }
            "Last Run at ``" + $(get-date) + "`` UTC" > Readme.md
        - name: action-push-local-changes to Master
          uses: reloc8/action-push-local-changes@1.0.0
          with:
            commit-message: Daily_messgaes.json changed
