# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: '30 6 * * *' 

jobs:
  personal-channel:
    runs-on : windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Setup Python
        uses: actions/setup-python@v3.0.0    
      - name: Python Pip Install
        uses: logikal-code/pip-install@v1.0.0
  
