# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-action
name: Birthday Update

on:
  schedule:
    - cron: '00 18 * * *' 
  workflow_dispatch:
  workflow_run:
    workflows: [Build]
    types:
      - completed
  repository_dispatch:
      types: [birthday-update]
jobs:
  trigger-bday-bot:
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN : ${{secrets.DISCORD_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - name: generate certificate file from secrets              
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "certificate.json"
          json: ${{ secrets.CERTIFICATE_INFO }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - name: Download required dependencies
        run: pip install -r requirements.txt
      - name: Run the program
        run: python main.py
