# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-action
name: Birthday Update

on:
  schedule:
    - cron: '00 18 * * *' 
  workflow_dispatch:
jobs:
  personal-channel:
    runs-on : windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Running the program
        run: ".\\main.exe"

  # You may pin to the exact commit or the version.
  # uses: reloc8/action-push-local-changes@db6ff4a3eac620530c970af02229a260240aa8aa
      - name : chnaged Readme.md
        run : |
          $FileName = "Readme.md"
          if (Test-Path $FileName) {
            Remove-Item $FileName
          }
          "Last Run at ``" + $(get-date) + "`` UTC" > Readme.md
      - name: action-push-local-changes to Master
        uses: reloc8/action-push-local-changes@1.0.0
        with:
          commit-message: Daily_messgaes.json changed
