# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: '15 6 * * *' 
  push: 
    branches : [master]
jobs:
  personal-channel:
    runs-on : windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Setup Python
        uses: actions/setup-python@v3.0.0    
      - name: Python Pip Install
        uses: logikal-code/pip-install@v1.0.0
      - name: Run Python Program
        run:  python main.py

  # You may pin to the exact commit or the version.
  # uses: reloc8/action-push-local-changes@db6ff4a3eac620530c970af02229a260240aa8aa
      - name : chnaged Readme.md
        run : |
          $FileName = "Readme.md"
          if (Test-Path $FileName) {
            Remove-Item $FileName
          }
          "Last Run at ``" + $(get-date) + "`` UTC" > Readme.md
      - name: action-push-local-changes to Master
        uses: reloc8/action-push-local-changes@1.0.0
        with:
          commit-message: Daily_messgaes.json changed
